name: Release

on:
  workflow_dispatch:
#on:
#  push:
#    tags:
#      - "v*.*.*"

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # with .nvmrc Node version
      - uses: dcodeIO/setup-node-nvm@master

      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn workspaces foreach -Rpt --from '*-cli' run build

      #- run: yarn run lint
      #- run: yarn run test

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            LICENSE
