name: Release

on:
  workflow_dispatch:
#on:
#  push:
#    tags:
#      - "v*.*.*"

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Read node version from `.nvmrc` file, and pass it to setup-node
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"

      - run: yarn install --immutable
      - run: yarn workspaces foreach -Rpt --from '*-cli' run build

      #- run: yarn run lint
      #- run: yarn run test

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            LICENSE
